### ISSUE TITLE
Issue with Microsoft Authentication

### ISSUE THREAD

**Issue by tketchup** [JohnKearney1/MineGPT#2]
Great work with MineGPT. I've run into an issue with the Microsoft authentication. I own a Microsoft account with Minecraft Java. After setting up the `config.json` file, I get this error when I try to run the script with my email address:

```bash
Starting MineGPT
Error: Failed to obtain profile data for ...@gmail.com, does the account own minecraft?
    at Object.authenticate (D:\MineGPT-2.1\node_modules\minecraft-protocol\src\client\microsoftAuth.js:31:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Although Microsoft needs the email address, I tried my ingame name and the error changed to:

```bash
Starting MineGPT
Sign in failed, try removing the password field

XboxReplayError: Invalid credentials.
    at Object.unauthorized (D:\MineGPT-2.1\node_modules\@xboxreplay\errors\dist\index.js:25:74)
    at D:\MineGPT-2.1\node_modules\@xboxreplay\xboxlive-auth\dist\core\live\index.js:71:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async XboxTokenManager.doReplayAuth (D:\MineGPT-2.1\node_modules\prismarine-auth\src\TokenManagers\XboxTokenManager.js:145:31)
    at async MicrosoftAuthFlow.getXboxToken (D:\MineGPT-2.1\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:122:20)
    at async retry.xbl.forceRefresh (D:\MineGPT-2.1\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:160:22)
    at async retry (D:\MineGPT-2.1\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:23:14)
    at async MicrosoftAuthFlow.getMinecraftJavaToken (D:\MineGPT-2.1\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:159:7)
    at async Object.authenticate (D:\MineGPT-2.1\node_modules\minecraft-protocol\src\client\microsoftAuth.js:22:58) {
  __XboxReplay__: true,
  details: { statusCode: 401, reason: 'UNAUTHORIZED' }
}
```

My credentials are correct and work fine manually. Any assistance would be appreciated. 
Thank you

**Comment by tketchup** [comment]
I've managed to solve the issue. The problem was with my newly created Microsoft account. Although I could log in, I hadn't launched Minecraft yet, and my account didn't have a username initially. After launching Minecraft and setting a username, everything works fine now.
Thank you

**Comment by JohnKearney1** [comment]
@tketchup Much Thanks!! I'll update to handle this case, or simply to clarify this in the docs.
